Task force meetings page
MAPC/metro-mayors-housing-task-force pull request #126
Opened 2024-10-31 15:46 UTC by navneetjoshi223

2024-10-31 16:20 UTC, anaximander requested changes
Overall looking pretty good, most changes I've requested are just removing unused code. I have some UI/UX feedback that send you directly in Slack.

2024-10-31 18:33 UTC, navneetjoshi223 commented on src/js/components/TaskForceMeetings.jsx
> +  // const columns = useMemo(
Removed it

2024-10-31 18:37 UTC, navneetjoshi223 commented on src/js/components/TaskForceMeetings.jsx
> +import { useTable } from "react-table";
yes I was experimenting with it. Removed the import since we're not using it!

2024-11-01 16:17 UTC, anaximander approved these changes
LGTM 👍 We can do another pass for styling later.

2024-11-01 16:56 UTC, merged